### <center> ASSIGNMENT

1. 

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

Yes, there is a difference between the two. list_ is of list data type whereas array_list is of numpy array data type. The differences between numpy array and list are as follows-   

i. Numpy array consumes less memory.  
ii. Numpy arrays are fast as compared to the Python Lists.  
iii. Numpy arrays are convenient to use.  

2. 

In [9]:
for x in list_:
    print(type(x))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for x in array_list:
    print(type(x))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
array_list.dtype

dtype('<U1')

3. 

In [13]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [14]:
for x in list_:
    print(type(x))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
for x in array_list:
    print(type(x))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
array_list.dtype

dtype('int64')

The data type of the elements of the numpy array have changed to integer(numpy.int64) from string(numpy.str_).

4. 

In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

5. 

In [26]:
zero_array=np.zeros((3,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
zero_array.shape

(3, 3)

In [28]:
zero_array.size

9

6. 

In [29]:
ones_array=np.eye(5)
ones_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
ones_array.shape

(5, 5)

In [31]:
ones_array.size

25